### ISSUE TITLE
Autocomplete field not working in case of collection type

### ISSUE THREAD

**Issue by SamyDahmani** [egeloen/IvoryGoogleMapBundle#112]
Hello,

I'm trying to use the autocomplete form as collection to be able to add many addresses, (OneToMany relation), the field is displayed but the autocomplete is not working.

$builder->add('addresses', 'collection', array('type' => new AddressFormType(),
                                                                       'allow_add'    => true,
                                           'allow_delete' => true));

The autocomplete is working fine whith the following:
$builder->add('addresses', new AddressFormType());

How can I make it working with collection type ?

Thank you.

**Comment by sourabh1801** [comment]
Hi I am getting attached error in my code

- I am getting error - "cannot read property 'replace' or undefined
