### ISSUE TITLE
Autocomplete Form Submission

### ISSUE THREAD

**Issue by soerenmartius** [egeloen/IvoryGoogleMapBundle#129]
Hi,

Whats the best way to submit the current form after a list entry was chosen? I dont want users to have to click on a submit button if the form only contains the places autocomplete field.

Thank you

**Comment by egeloen** [comment]
Your issue has been fixed in #159 but will only be part of the 3.x version of the bundle.

As already suggested, the solution is to use events. Something like the following would do the job:

``` php
$builder->add('field', PlaceAutocompleteType::class, [
    'variable' => $variable = 'acme_place_autocomplete',
    'events' => [new Event(
        $variable,
        'place_changed',
        'function ( /* Handle your automatic form submission... */ )'
    )]
]);
```
