### ISSUE TITLE
Drawing a path

### ISSUE THREAD

**Issue by ricardoalmira89** [egeloen/IvoryGoogleMapBundle#131]
hi guys.
I need to draw a path between two coordinates. I did this:

foreach ($response->getRoutes() as $route)
        {
            foreach ($route->getLegs() as $leg)
            {
                foreach ($leg->getSteps() as $step) {
                    $instructions->add($step->getInstructions());
                    $polyline->addCoordinate($step->getStartLocation()->getLatitude(), $step->getStartLocation()->getLongitude(),true);
                }
            }
        }
        $map->addPolyline($polyline);

but isn´t enough. This code draws rect lines  and i need to draw them inside the roads, like a really path. I´ve been reading the documentation inside the bundle and it seems that a good way to make it work is with DirectionStep, using getEncodedPolyline getter. I tried $map->addEncodedPolyline($encodedP) but the map dont render the polyline.
Thanks.

**Comment by egeloen** [comment]
Your issue has been fixed in #159 (encoded polyline works again) but will only be part of the 3.x version of the bundle.
