### ISSUE TITLE
Hide markers with javascript?

### ISSUE THREAD

**Issue by jernejpangersic** [egeloen/IvoryGoogleMapBundle#135]
Hi,

I'm using your great bundle to show lots of locations on the map, using markers.
I have about 12 different markers that I'm using.
My question is, if I can some how make a "filter" button, that would hide one of the categories?

For example - I have markers for "Cemeteries". And would like to make a button that would hide/show those locations. Is this possible?

Thanks!

**Comment by Id4v** [comment]
:+1: 
Would be nice.
@jernejpangersic did you find a way to do it?

**Comment by egeloen** [comment]
Given you have a marker with a fixed variable:

``` php
$marker = new Marker();
$marker->setVariable('my_marker');
```

Then, in your javascript code, you can use the following do hide the marker:

``` js
my_marker.setMap(null);
```
