### ISSUE TITLE
Places autocomplete not loading when IvoryGoogleMapBundle loaded before TwigBundle

### ISSUE THREAD

**Issue by WhatsOn** [egeloen/IvoryGoogleMapBundle#137]
I stumbled upon a this when I sorted my bundles in the kernel :)

When You load IvoryGoogleMapBundle before TwigBundle, the "twig.form.resources" parameter gets overwritten (when Twig loads), and places_autoload_widget.html.twig template is ignored when rendering forms. This results in the field being rendered as a plain text field -> no 'javascripts'  template variable printed -> google API not loaded -> maps and places not working.

I suggest moving the template registration to a CompilerPass instead, so as not to rely on TwigBundle being loaded before IvoryGoogleMapBundle.

**Comment by egeloen** [comment]
Thanks for reporting it! It has been fixed in #160 but will only be part of the 3.x version of the bundle.
