### ISSUE TITLE
[Geocoder] geocode() return GeocoderResult, not implementing ResultInterface

### ISSUE THREAD

**Issue by jcrombez** [egeloen/IvoryGoogleMapBundle#138]
Hello ! :)

The class **Ivory\GoogleMap\Services\Geocoding\Geocoder** extends **Geocoder\Geocoder\BaseGeocoder** which implements **Geocoder\GeocoderInterface**.

This interface specify that **geocode()** return a **Geocoder\Result\ResultInterface** but **Ivory\GoogleMap\Services\Geocoding\Geocoder** return a **Ivory\GoogleMap\Services\Geocoding\Result\GeocoderResponse** which does not implment nor follow this interface.

Am i missing something or is this a real issue ?

**Comment by ReservedDeveloper** [comment]
The flip side of this issue (IvoryGoogleMap says it returns GeocoderResponse, but docblocks say ResultInterface) can be seen here: https://github.com/egeloen/ivory-google-map/issues/106.

**Comment by egeloen** [comment]
Your issue has been fixed in the library.
