### ISSUE TITLE
Pass additional options into adapter

### ISSUE THREAD

**Issue by ekut** [egeloen/IvoryGoogleMapBundle#139]
I needed to pass additional options in CurlHttpAdapter, specifically
CURLOPT_FOLLOWLOCATION
However, I was not able to do it through the config.yml
How can I pass additional options into Geocoder\HttpAdapter\CurlHttpAdapter::__construct() ?

Sorry for my terrible English.

**Comment by egeloen** [comment]
Your issue has been fixed in #159 but will ony be part of the 3.x version of the bundle. We now rely on [Httplug](http://httplug.io/) for issuing http requests.
