### ISSUE TITLE
(re)loading markers dynamically with AJAX?

### ISSUE THREAD

**Issue by zangai** [egeloen/IvoryGoogleMapBundle#140]
Hi,

I would like to know if the plugin supports a scenario where I can update the markers of the map based on a filter, and have them being populated, preferable based on a JSON structure?

**Comment by Id4v** [comment]
:+1: 
I'd like to know if this is possible too.
@zangai did you found a way to do it?

**Comment by elernonelma** [comment]
We do it manually do it here. You just need to manipulate the google api, by removing old markers / adding new ones.

**Comment by egeloen** [comment]
Closing as this is out of scope of the library/bunde.
