### ISSUE TITLE
Marker as links 

### ISSUE THREAD

**Issue by Sashkan** [egeloen/IvoryGoogleMapBundle#141]
I noticed the "clickable" option on the markers, is it possible to configure them as link ? I have a map with a few cities, I'd like to link them to some HTML links.

Thank you, and great work !

**Comment by egeloen** [comment]
I would use this answer: http://stackoverflow.com/questions/8769966/google-map-api-open-url-by-clicking-at-marker#answer-8770321

Build a marker with a extra param:

``` php
$marker = new Marker();
$marker->setOption('url', 'your-url-data');
```

And then attach an event for each marker

``` php
$map->getEventManager()->addEvent(new Event(
    $marker->getVariable(),
    MouseEvent::CLICK,
    'function () { window.location.href = this.url; }'
))
```
