### ISSUE TITLE
marker shape 

### ISSUE THREAD

**Issue by wieslawbrzozowski** [egeloen/IvoryGoogleMapBundle#142]
Hi

I you trying to use a marker shape as the following code, but the marker does not appear on the map.

$marker = new Marker();
$markerShape = new MarkerShape();
$markerShape->setPrefixJavascriptVariable('marker_shape_');
$markerShape->setType('poly');
$markerShape->setCoordinates(array(1, 1, 1, -1, -1, -1, -1, 1));

$marker->setShape($markerShape);

In addition, other markers with icons, also stop working. Can you help me. Maybe I'm doing something wrong. 

Thank you and best regards

**Comment by egeloen** [comment]
Here, a functional test using a marker shape: https://github.com/egeloen/ivory-google-map/blob/master/tests/Helper/Functional/Overlay/MarkerFunctionalTest.php#L73-L84
