### ISSUE TITLE
IvoryGoogleMapBundle + AngularJS

### ISSUE THREAD

**Issue by durancu** [egeloen/IvoryGoogleMapBundle#144]
Hi @egeloen!
I need to load a map for the distribution of shops on a city. I want to change a city, with a combobox, and then refresh or reload the map with markers associated to the new city. Can I reload a map using AngularJS, without reload the page?
Thanks in advanced

**Comment by robations** [comment]
Happened to see this issue. I hope you already found a solution... but you might be best off using a directive to render the map, and I think I saw in another issue that you can render your IvoryGoogleMap structure using JsonRender, so you could link the two using $http.

https://github.com/angular-ui/angular-google-maps might be of use

**Comment by egeloen** [comment]
Since the bundle is server side, I'm not sure that this bundle is the right choice...
