### ISSUE TITLE
The "factory-method" attribute and "factory-service" are deprecated

### ISSUE THREAD

**Issue by chandon** [egeloen/IvoryGoogleMapBundle#145]
is deprecated since version 2.6 and will be removed in 3.0. Use the "factory" element instead. 

xml to correct in Resources\config\services\*.xml

**Comment by stijink** [comment]
+1

**Comment by simonchrz** [comment]
fixed in #151

**Comment by chandon** [comment]
Thanks @simonchrz but i think it'll never be merged, because this bundle is not maintained anymore...

**Comment by simonchrz** [comment]
mmh... any other current bundles out there ?

**Comment by egeloen** [comment]
Your issue has been fixed in #159 but will on be part of the 3.x version of the bundle.
