### ISSUE TITLE
google Map Symfony2

### ISSUE THREAD

**Issue by rimariahiriri** [egeloen/IvoryGoogleMapBundle#152]
Good evening,
there is a video to explain how I used egeloen / ivoryMapBundle because I have tried many but no display.

**Comment by rimariahiriri** [comment]
I added egeloen / google-map-bundle: ~ 2.1 in my composer.json,
and after I add new Ivory \ GoogleMapBundle \ IvoryGoogleMapBundle () in my app / AppKernel.php
, After I did a simple test but nothing appears, I'm still trying and I created a new bundle name Ivory \ IvoryGoogleMapBundle, and also does not display anything

**Comment by Alphanumerix** [comment]
This bundle is no longer maintained. You can use it though, but it won't work for Symfony3+.

**Comment by rimariahiriri** [comment]
Bonjour,
ui je veux l'utiliser pour le symfony2, mais je n'ai pas connais comment ?
s'il vous plais m'aide.

2016-03-02 11:50 GMT+01:00 Konrad Mski <notifications@github.com>:

**Comment by Alphanumerix** [comment]
https://github.com/egeloen/IvoryGoogleMapBundle/blob/master/Resources/doc/usage.md

Install Bundle, then in action in controller:
> $map = $this->get('ivory_google_map.map');
and send it to the template (.html.twig).

In template use:
{{ google_map(map) }}

And that's it. Open given web page and make sure:

- there is no 404/js errors in console
- rendered code is visible (might be css fix related)

**Comment by rimariahiriri** [comment]
Ok un grand merci MSR , je vais essayer une autre fois .Merci

2016-03-03 10:32 GMT+01:00 Konrad Mski <notifications@github.com>:

**Comment by rimariahiriri** [comment]
Good evening, I did as I say but that the result is this-I have to do a nv
Bundle src above and copy all the google-map-bundle file? or what ?
[image: Images intégrées 1]

2016-03-03 13:23 GMT+01:00 riahi rim <riahi.rim14@gmail.com>:

**Comment by rimariahiriri** [comment]
Good evening, I like to tell me but the result was a simple map without action is this-I have to do a nv Bundle src above and copy all the google-map-bundle file? or what ?

**Comment by rimariahiriri** [comment]
Good evening, I like to tell me but the result was a simple map without
action is this-I have to do a nv Bundle src above and copy all the
google-map-bundle file? or what ?

2016-03-03 20:23 GMT+01:00 riahi rim <riahi.rim14@gmail.com>:

**Comment by KevinArtus** [comment]
Hi @rimariahiriri 

You need to add event to the map ? I mean, you want to add event on map when you click or something like that ? I need to do it but i do not know how it work :/ Do you have find a solution ?

**Comment by rimariahiriri** [comment]
hi, KevinArtus
yes I tried and I found a simple solution

**Comment by rimariahiriri** [comment]
No. I asked myself even a video to explain how the map in symfony

**Comment by KevinArtus** [comment]
Hi @rimariahiriri 
Could you, please, share it with me ? I need to add onClick event on my map but i do not understand this line (https://github.com/egeloen/ivory-google-map/blob/master/doc/usage/events.md) :
Event name
Each object has his own event name which are described in the google map documentation.

If you have find a way to do that, i need your help =)
Thank you.

**Comment by Alphanumerix** [comment]
@KevinArtus @rimariahiriri 
Hi guys. Sorry for delay. I will dig up some old project and paste some snippets in here later today.

Remember that this Bundle is not maintained anymore.
