### ISSUE TITLE
googole Map Symfony2

### ISSUE THREAD

**Issue by rimariahiriri** [egeloen/IvoryGoogleMapBundle#153]
Good evening,
there is a video to explain how I used egeloen / ivoryMapBundle because I have tried many but no display.

**Comment by KevinArtus** [comment]
Hello,

You have made a video to explain how you used it ? If yes, i'm interested by your video. Could you please share me a link ?

**Comment by egeloen** [comment]
Sorry but making a video in not on my TODO list...
