### ISSUE TITLE
Symfony 3 Compatibility

### ISSUE THREAD

**Issue by JimmyTournemaine** [egeloen/IvoryGoogleMapBundle#154]
Is it planned to make this bundle compatible with Symfony 3 ?

**Comment by KevinArtus** [comment]
This bundle has not been updated since 2 years. I do not think that it will be updated for Symfony 3.
But, i used it on Symfony 2.8.4 and it work well. I have not had any problems.

**Comment by clytemnestra** [comment]
Aren't there other people willing to maintain it? Or is there something similar to it?

**Comment by KevinArtus** [comment]
It seems none want to maintain it to Symfony 3.
I did not get any problems with Symfony 2.8.4.

I would like to maintain it but i've dont have time :/

**Comment by clytemnestra** [comment]
Pretty sure a lot of people would love to maintain it but nobody has time indeed. Biggest problem of open source.

**Comment by KevinArtus** [comment]
Yes of course !
There is the problem of the open source... I'm working on a open source project for my job but i do not have the time to spend my free time to develop other open source project.
BTW, this bundle is really good, it helped me a lot.

**Comment by handosensei** [comment]
Hello,

Can you list the task in order to update the bundle please ?
Give us some instruction to do this please.

**Comment by wholehogsoftware** [comment]
@egeloen Said he's not maintaining it because he doesn't use it anymore.

**Comment by fungio** [comment]
I made fork for sf 3.1 if any of you is interested
https://packagist.org/packages/fungio/google-map-bundle

**Comment by markbijl** [comment]
Hi @fungio !

Actually, I _am_ interested, and thank you for pointing it out! I'm sure going to give that a try, and maybe @egeloen might consider merging your work back in to the master...?

It does make me wonder if @egeloen said he is not maintaining it because he's no longer using it, what are indeed possible alternatives? Anyone recommendations?

Thanks!

**Comment by wholehogsoftware** [comment]
@egeloen mentioned not wanting to maintain this anymore so maybe he could give maintenance control to @fungio and others could make use of it?

Thanks @fungio for your work. Much appreciated.

**Comment by fungio** [comment]
It's too bad he is not maintaining it anymore ! It's a really good bundle, very useful ! I'm sure lot of people are using it ! I sure do !

**Comment by titolendable** [comment]
@fungio thanks for forking this repository, but why only for Symfony 3.1? And I couldn't add an issue on your branch, where this message would make more sense to be posted.

**Comment by fungio** [comment]
Yep sorry issues were not enabled. It is now.
I needed it to work with 3.1 but it could definitely work with other versions. Just make an issue I'll work on it ;)

**Comment by egeloen** [comment]
Your issue has been fixed by #159 but will only be part of the 3.x version of the bundle.
