### ISSUE TITLE
Google Map Not Available

### ISSUE THREAD

**Issue by nickworker** [egeloen/IvoryGoogleMapBundle#156]
Google Map Not Available http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer_compiled.js
moved to github
Also i trying to reload Ivory\GoogleMap\Helper\Overlays\MarkerCluster\JsMarkerClusterHelper
by params but it hardcoded in 
Ivory\GoogleMap\Helper\Overlays\MarkerCluster\MarkerClusterHelper 

Then I Trying To Reload  Helper just using helper_class: "My\Fucking\MarkerHelper"
https://github.com/egeloen/IvoryGoogleMapBundle/blob/master/Resources/doc/usage/overlays/marker_cluster.md#build-your-marker
AND Get

Catchable Fatal Error: Argument 1 passed to Ivory\GoogleMap\Helper\Overlays\MarkerCluster\AbstractMarkerClusterHelper::__construct() must be an instance of Ivory\GoogleMap\Helper\Overlays\MarkerHelper, array given 

So provide Some Examples please.

**Comment by xmon** [comment]
Did you solve it?

**Comment by egeloen** [comment]
Your issue has been fixed by #159 but will only be part of the 3.x version of the bundle.
