### ISSUE TITLE
Symfony 3

### ISSUE THREAD

**Issue by markbijl** [egeloen/IvoryGoogleMapBundle#158]
Hi Eric,

First of all congratulations with a nice and useful bundle! I wanted to use the bundle in a new Symfony 3 project that I am starting, however, I ran into a Composer challenge as it won't install the package due to various dependency issues.

Are you planning to support Symfony 3?

Thanks in advance!
Regards,
Mark

p.s. you might also consider updating your release description, as this command no longer works:
`composer require egeloen/google-map-bundle: ~2.1`

**Comment by odecharette** [comment]
same for me !

**Comment by JimmyTournemaine** [comment]
#154 Someone already update the bundle for Symfony 3. I doesn't test it yet but it seems right !

**Comment by egeloen** [comment]
Your issue has been fixed by #159 but will only be part of the 3.x version of the bundle.

**Comment by markbijl** [comment]
@egeloen Much obliged! I'm gonna give the dev-master a try in my Symfony 3 project!
