### ISSUE TITLE
Trying to load a non-existent file UnionExtendableRenderer

### ISSUE THREAD

**Issue by markbijl** [egeloen/IvoryGoogleMapBundle#164]
I just tried the latest dev branches of the Bundle and its library, but I get the following error:

`Attempted to load class "UnionExtendableRenderer" from namespace "Ivory\GoogleMap\Helper\Renderer\Overlay\Extendable".`

I went all adventurous by requesting both as dev:
```
    "egeloen/google-map": "@dev",
    "egeloen/google-map-bundle": "@dev",
```

However, the requested file seems not to be present, though an Abstract variant resides in the referenced directory..?

Any recommendations?

Thanks in advance!

**Comment by markbijl** [comment]
BTW @egeloen I see you've been quite busy, cudo's for all the hard work so far!

**Comment by egeloen** [comment]
I just realize I don't have updated the bundle according to egeloen/ivory-google-map#161 I will fix it tonight.

**Comment by markbijl** [comment]
Much obliged, and thanks for the speedy reply!

**Comment by egeloen** [comment]
Your issue has been fixed in the referenced PR.

**Comment by markbijl** [comment]
Confirmed! Thanks for the speedy fix, building a few nice maps now thanks to you!
