### ISSUE TITLE
Is there an example of config.yml to use

### ISSUE THREAD

**Issue by heronour** [egeloen/IvoryGoogleMapBundle#168]
Is there an example of config.yml to use with this bundle, and an example of twig vue (I have some issues with google API key)
Thanka a lot :)

**Comment by markbijl** [comment]
Hi @heronour,

I believe this page in the documentation is what you might be looking for:
https://github.com/egeloen/IvoryGoogleMapBundle/blob/master/Resources/doc/map.md

**Comment by heronour** [comment]
Hello @markbijl 
Thanks a lot for your response,
I have used the precedure after cloning the the bundle (from githube) to my vennder directory 
And I gote this error:

> InvalidArgumentException in RegisterListenersPass.php line 104: Class "Ivory\GoogleMap\Helper\Subscriber\ApiJavascriptSubscriber" used for service "ivory.google_map.helper.subscriber.api_javascript" cannot be found.

**Comment by markbijl** [comment]
Hi @heronour 

I am only a novice user of the library, but did you include both the IvoryGoogeMapBundle and the IvoryGoogleMap libraries? They are both required... BTW: unless you are planning customizing the libraries for yourself, might as well use Composer..?

Cheers

**Comment by heronour** [comment]
It works fine now, I have cloned the other repo "ivory-google-map"
Thanks  :)

**Comment by egeloen** [comment]
@markbijl is right.  Additionally, if you want to know more about a bundle config, you can use:

``` bash
$ php bin/console config:dump-reference ivory_google_map
```

**Comment by heronour** [comment]
Thanks @egeloen ;)
