### ISSUE TITLE
place autocomplete not working

### ISSUE THREAD

**Issue by chimneysweep13** [egeloen/IvoryGoogleMapBundle#169]
Hello,
place autocomplete feature seems not working.
In #80 place autocomplete support was added, and it also added `IvoryGoogleMapBundle:Form:places_autocomplete_widget.html.twig` to `twig.form.resources`. Later in #159 all this stuff was removed from `DependencyInjection/IvoryGoogleMapExtension.php`.

Now we have `{% block places_autocomplete_widget %}` in https://github.com/egeloen/IvoryGoogleMapBundle/blame/master/Resources/views/Form/place_autocomplete_widget.html.twig#L1 but block prefix in https://github.com/egeloen/IvoryGoogleMapBundle/blob/master/Form/Type/PlaceAutocompleteType.php#L144 is `place_autocomplete` (difference in additional *S* at the end of place).

Downside is that form theme is not loaded automatically, but after all if you add it manually to your config/template it is not used because of bad block prefix name.

Am I misunderstanding something and using this bundle not properly or is it bug? If so just let me know and maybe I can submit PR with fix.

**Comment by egeloen** [comment]
Thanks for reporting it! Indeed, I forgot to remove the "s" from the twig block when refactoring... I should probably introduce more robust tests about templates...

Be aware, the form_theme is still loaded automatically but via a compiler pass: https://github.com/egeloen/IvoryGoogleMapBundle/blob/master/DependencyInjection/Compiler/RegisterFormResourcePass.php

**Comment by chimneysweep13** [comment]
Thanks for information. Compiler pass is working as you wrote, so probably I had some mess in code before which results in not working properly. 
Fix is also submitted.
