### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by wieslawbrzozowski** [egeloen/IvoryGoogleMapBundle#175]
I install symfony 
3.1, 3.0 

I try install bundle by composer
$ composer require egeloen/google-map-bundle

and I can`t I have error, can you halp me ?

  Problem 1
    - Conclusion: remove symfony/symfony v3.0.9
    - Conclusion: don't install symfony/symfony v3.0.9
    - egeloen/google-map-bundle 2.2.0 requires symfony/framework-bundle ~2.1 ->                                                                                              satisfiable by symfony/framework-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.1                                                                                             2, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2                                                                                             .0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2                                                                                             .2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.                                                                                             15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.                                                                                             23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.                                                                                             31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3                                                                                             .4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v                                                                                             2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9,                                                                                              v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.                                                                                             6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v                                                                                             2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v                                                                                             2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.2, v                                                                                             2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v                                                                                             2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - egeloen/google-map-bundle 2.2.1 requires symfony/framework-bundle ~2.1 ->                                                                                              satisfiable by symfony/framework-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.1                                                                                             2, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2                                                                                             .0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2                                                                                             .2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.                                                                                             15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.                                                                                             23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.                                                                                             31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3                                                                                             .4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v                                                                                             2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9,                                                                                              v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.                                                                                             6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v                                                                                             2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v                                                                                             2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.2, v                                                                                             2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v                                                                                             2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - don't install symfony/framework-bundle v2.3.0|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.3.1|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.3.10|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.11|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.12|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.13|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.14|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.15|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.16|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.17|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.18|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.19|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.2|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.3.20|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.21|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.22|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.23|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.24|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.25|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.26|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.27|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.28|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.29|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.3|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.3.30|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.31|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.32|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.33|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.34|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.35|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.36|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.37|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.38|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.39|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.4|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.3.40|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.41|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.42|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.3.5|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.3.6|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.3.7|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.3.8|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.3.9|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.4.0|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.4.1|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.4.10|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.4.2|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.4.3|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.4.4|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.4.5|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.4.6|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.4.7|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.4.8|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.4.9|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.5.0|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.5.1|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.5.10|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.5.11|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.5.12|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.5.2|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.5.3|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.5.4|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.5.5|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.5.6|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.5.7|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.5.8|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.5.9|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.6.0|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.6.1|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.6.10|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.6.11|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.6.12|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.6.13|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.6.2|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.6.3|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.6.4|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.6.5|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.6.6|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.6.7|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.6.8|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.6.9|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.7.0|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.7.1|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.7.10|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.7.11|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.7.12|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.7.13|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.7.14|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.7.15|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.7.16|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.7.17|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.7.2|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.7.3|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.7.4|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.7.5|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.7.6|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.7.7|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.7.8|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.7.9|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.8.0|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.8.1|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.8.2|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.8.3|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.8.4|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.8.5|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.8.6|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.8.7|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.8.8|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.8.9|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.1.0|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.1.1|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.1.10|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.1.11|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.1.12|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.1.13|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.1.2|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.1.3|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.1.4|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.1.5|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.1.6|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.1.7|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.1.8|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.1.9|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.2.0|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.2.1|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.2.10|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.2.11|don't install symfony/symfo                                                                                             ny v3.0.9
    - don't install symfony/framework-bundle v2.2.2|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.2.3|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.2.4|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.2.5|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.2.6|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.2.7|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.2.8|don't install symfony/symfon                                                                                             y v3.0.9
    - don't install symfony/framework-bundle v2.2.9|don't install symfony/symfon                                                                                             y v3.0.9
    - Installation request for symfony/symfony == 3.0.9.0 -> satisfiable by symf                                                                                             ony/symfony[v3.0.9].
    - Installation request for egeloen/google-map-bundle ^2.2 -> satisfiable by                                                                                              egeloen/google-map-bundle[2.2.0, 2.2.1].

**Comment by egeloen** [comment]
@wieslawbrzozowski Thanks for reporting it! Basically, the next major version is comming but is not finished yet. SO, if you want to get the last changes and also be able to use it with Symfony3, you need to install the following:

``` json
{
    "require": {
        "egeloen/google-map": "^2.0@dev`,
        "egeloen/google-map-bundle": "^3.0@dev"
    }
}
```

When the next major version will be released, you can replace it with:

``` json
{
    "require": {
        "egeloen/google-map-bundle": "^3.0"
    }
}
```
