### ISSUE TITLE
How to configure api key?

### ISSUE THREAD

**Issue by Isinlor** [egeloen/IvoryGoogleMapBundle#176]
I'm using latest 2.2.1 version.

Regex search for `api?key` gives nothing.

This documentation is not right:
https://github.com/egeloen/IvoryGoogleMapBundle/blob/master/Resources/doc/service/distance_matrix.md#api-key

This as well:
https://github.com/egeloen/IvoryGoogleMapBundle/blob/master/Resources/doc/map.md#api-key

How should it be done?

**Comment by egeloen** [comment]
First, thanks for taking taime to report it but unfortunatelly, there is nothing to fix...

Let me explain your issue, when refering to https://github.com/egeloen/IvoryGoogleMapBundle/blob/master/Resources/doc/service/distance_matrix.md#api-key you're refering to `dev-master` doc whereas if you're using the 2.2.1 version, you should use: https://github.com/egeloen/IvoryGoogleMapBundle/blob/2.2.1/Resources/doc/usage/services/distance_matrix/distance_matrix.md

Unfortunatelly for you, the api key support has only been added on master, so if you want to take benefit of it, you will need to upgrade.

**Comment by Isinlor** [comment]
Thanks for help. Just one more question - how much instability can I expect on `dev-master`?

**Comment by egeloen** [comment]
Dependending what do you mean by stable :) If by stable, you mean it works, yes it works :) but if you mean no BC breaks I can't say I will not introduce BC breaks before releasing the next major release... I'm currently reworking the services. It will still work the same way but I will maybe break the way to create a service in a near future...

**Comment by egeloen** [comment]
Closing as the issue has been resolved :)
