### ISSUE TITLE
Could not load type "Ivory\GoogleMapBundle\Form\Type\PlaceAutocompleteType"

### ISSUE THREAD

**Issue by sluzux** [egeloen/IvoryGoogleMapBundle#177]
Hello, 
I m trying to integrate the autocomplete in my LocationType.php form, but I keep getting the the error : Could not load type "Ivory\GoogleMapBundle\Form\Type\PlaceAutocompleteType".
The bundle is installed and active in the kernel , and i followed the instructions on https://github.com/egeloen/IvoryGoogleMapBundle/blob/master/Resources/doc/place_autocomplete.md .

this is my LocationType.php 
```

use Ivory\GoogleMap\Place\AutocompleteType;
use Ivory\GoogleMapBundle\Form\Type\PlaceAutocompleteType;
use Vich\UploaderBundle\Form\Type\VichImageType;

class LocationType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', PlaceAutocompleteType::Class)
            ->add('status', HiddenType::Class, array('empty_data'=>'1'))
            ->add('dateIns', HiddenType::Class, array('data'=>'nowdate'))
            ->add('description', TextareaType::Class)            
            ->add('category', ChoiceType::Class, array( 'choices'=> array(
                                                'Beach'=>'beach',
                                                'Mountain'=>'Mountain',
                                                'Town'=>'town',
                                                'Natural Reserve'=>'natural_reserve')))
            ->add('imageFile', FileType::Class, array('required'=>false))
            ->add('imageName', HiddenType::Class, array('empty_data'=>null));
            
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Location'
        ));
    }
}
```
 
the version on my composer is this : "egeloen/google-map-bundle": "^2.2" 
Maybe I need to add any other use ?

**Comment by egeloen** [comment]
It takes a moment to understand what's going ont but at the end, it is related to the version of the bundle you rely. The doc you refer (https://github.com/egeloen/IvoryGoogleMapBundle/blob/master/Resources/doc/place_autocomplete.md) refers to `dev-master` whereas if you want to use the place autocomplete on 2.2, you should rely on https://github.com/egeloen/IvoryGoogleMapBundle/blob/2.2.1/Resources/doc/usage/places/autocomplete.md

Be aware the library is not able to render a map and an autocomplete on the same page on the 2.2 version of the library. This issue has been addressed on master.

**Comment by egeloen** [comment]
Closing as according to the tests, the form type is loadable.
