### ISSUE TITLE
Missing API KEY

### ISSUE THREAD

**Issue by horusagency** [egeloen/IvoryGoogleMapBundle#180]
Hi, i'm using 2.2 version and api always appears key error ("Missing api key") . In config.yml 
ivory_google_map:
    api:
    geocoder:
        provider:
            api_key: "myapikey" 
In my controller  

$map = $this->get('ivory_google_map.map');
.... "map" => $map

In my twig view :     

{{ google_map_container(map) }}
{{ google_map_js(map) }}

Where is the problem?

Thank.

**Comment by hdnick** [comment]
I have the same problem

**Comment by egeloen** [comment]
You're both right. The api key is not supporrted on 2.x version but will be for the 3.x one. Sorry for that but I prefer focus on the 3.x for now.
