### ISSUE TITLE
PlaceAutocompleteType: Google Maps API multiple times on a page

### ISSUE THREAD

**Issue by aarsla** [egeloen/IvoryGoogleMapBundle#185]
Hello,
I am trying to use two PlaceAutocompleteType fields in one modal form.
However, only one of the fields is working.

![screen shot 2016-11-16 at 10 39 48](https://cloud.githubusercontent.com/assets/1655679/20342166/9e7f844e-abe9-11e6-9113-c2a934d0d0a3.png)

There is "You have included the Google Maps API multiple times on this page. This may cause unexpected errors" message presented in firebug console.

I am using google-map-bundle dev-master (google-map ^2.0@dev).

Thanks!

**Comment by egeloen** [comment]
Thanks for reporting this issue! This is weird... I have never give a try to this specific use case (multiple places autocomplete on the same page) but in theory, this use case should be handled... 

I will need to give a try to this use case and investigate.

**Comment by egeloen** [comment]
I just give a try to your issue in https://github.com/egeloen/ivory-google-map-issue-185/blob/master/index.php and it works as expected so, it should be related to something you do on your side. Can you copy/paste the way you render your autocompletes as well as the api loading?

**Comment by aarsla** [comment]
Thanks for a quick response!
Autocomplete fields are called from LegFormType:

`$builder->add('startLocation', 'AppBundle\Form\LocationType', [
                'label' => 'Start city'
            ])
            ->add('endLocation', 'AppBundle\Form\LocationType', [
                'label' => 'End city'
            ])
        ;`

They are two one-to-one fields (Lag has two Locations - startLocation and endLocation)

Locations are defined in LocationFormType

` $builder->add('city', PlaceAutocompleteType::class, [
            'label' => false,
            'types' => [AutocompleteType::CITIES],
            'attr' => [
                'style' => 'width:100%'
            ],
        ]);`

and rendered as regular form fields:

`{{ form_row(form.startLocation) }} {{ form_row(form.endLocation) }}`

Thanks!

**Comment by egeloen** [comment]
Ok thanks, I will try to reproduce it with your informations.

**Comment by egeloen** [comment]
@aarsla I just found why you get this error when using the bundle. Basically the bundle is designed to work  easily/transparently when you're using one autocomplete in a page. If you want to use multiple autocompletes on the same page you will need to do extra configuration...

The first one is to disable the autocomatic API loading. See https://github.com/egeloen/IvoryGoogleMapBundle/blob/master/Resources/doc/place_autocomplete.md#configure-api

Then, in your `javascripts` twig block add the following:

``` twig
{% block javascripts %}
     {{ parent() }}
     {{ ivory_google_api([form1.vars['autocomplete'], form2.vars['autocomplete']]) }}
{% endblock %}
```

**Comment by aarsla** [comment]
Awesome,
This does work directly on PlaceAutocompleteType and should definitely find its place in the cookbook documentation section (although maybe I have simply missed it).

One thing to note is that this will not work directly on embedded forms (as in my example):

> Key "autocomplete" for array with keys "value, attr, form, id... does not exist in... _form.html.twig

unless the embedded form field is referenced: 

`{{ ivory_google_api([form.subform.field1.vars['autocomplete'], form.subform.field2.vars['autocomplete']]) }}`

Thank you for your help again!
