### ISSUE TITLE
API Key Setup

### ISSUE THREAD

**Issue by dahomz** [egeloen/IvoryGoogleMapBundle#191]
Hi, i'm looking forward to using this bundle with our symfony 2.8 application.  Unfortunately, i've been having a few issues getting a simple map working.  It displays momentarily, and then the following error is displayed.  Looking at the javascript log, it appears to be related to not sending the the API key;

![image](https://cloud.githubusercontent.com/assets/11965232/21564009/02ff00f8-ce80-11e6-9986-c13a7ae32785.png)

Our setup was performed by "composer require egeloen/google-map-bundle" which installs ^2.2 version.

In the controller, using a very simple example derived from the docs;

`$map = new Map();`
`$map->setAutoZoom(false);`
`$map->setCenter(new Coordinate(0, 0));`
`$map->setMapOption('zoom', 3);`
`return $this->render('google_map.html.twig', array('map' => $map));`

In the twig template
`{{ google_map_container(map) }}`
`{{ google_map_js(map) }}`

When trying to set API key in config.yml

`ivory_google_map:`
`   api_key: "%google_map_api_key%"`
But this results in an error 'Unrecognized option "api_key" under "ivory_google_map"'

Please could you kindly suggest where i'm going wrong.  Many thanks in advance.

**Comment by muspelheim** [comment]
@egeloen Hi, can you please provide any info about this issue? I have same problem(

it's my composer string:
```log
"egeloen/google-map-bundle": "^2.2",
```

**Comment by David-DomaineLegal** [comment]
@egeloen Hello, same for me.

Work perfectly on localhost, but not on server.
same version than @muspelheim

**Comment by muspelheim** [comment]
@David-DomaineLegal you need upgrade to 3.0@dev version your google-map lib and google-map-bundle and all will be works great. this solution resolve my problem

**Comment by Pasttaga** [comment]
@muspelheim that what i currently doing.
Thanks :)

**Comment by egeloen** [comment]
Mostly due to this error (missing API key), the 2.x version of this bundle has becomed down... Since I was rewriting the library/bundle in order to fix architecture issue, I have fixed it in the upcoming 3.x version so if you want to use this bundle, you need to use the following since I release the next major release:

``` php
{
    "require": {
        "egeloen/google-map-bundle": "^3.0@dev",
        "egeloen/google-map": "^2.0@dev"
    }
}
``` 

When I will release it, you just have to replace this part by:

``` php
{
    "require": {
        "egeloen/google-map-bundle": "^3.0"
    }
}
```
