### ISSUE TITLE
Marker cluster icons unavailables

### ISSUE THREAD

**Issue by davidromani** [egeloen/IvoryGoogleMapBundle#193]
I need to render a GMap with clustered markers. My code is:

```php
$map = new Map();
$map->setStylesheetOption('width', '100%');
$map->setStylesheetOption('height', '450px');
$map->setMapOptions([
      'mapTypeId' => MapTypeId::ROADMAP,
      'zoom' => 10,
]);

foreach ($companies as $company) {
    $coordinates = new Coordinate($company->getLat(), $company->getLng());
    $marker = new Marker(
          $coordinates,
          Animation::DROP,
          new Icon($this->ah->getUrl('img/kinder-marker.png'))
    );
    $map->getOverlayManager()->getMarkerCluster()->addMarker($marker);
}

$map->getOverlayManager()->getMarkerCluster()->setType(MarkerClusterType::MARKER_CLUSTERER);
```

Everything works well, but my map doesn't show cluster icons. My web console output is:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://myapp.dev/app_dev.php/images/m1.png
```

What can I do?

**Comment by egeloen** [comment]
Hey @davidromani !

I just check quickly in the code which is responsible to render the marker cluster (https://github.com/egeloen/ivory-google-map/blob/master/src/Helper/Renderer/Overlay/MarkerClustererRenderer.php) and I don't see anything specific to assets/images management. I need to give it a try more deeply but for now, I don't know why the cluster icon cannot be resolved...

As a workaround, there is probably an option which allow to customize the cluster icon on the cluster manager.

**Comment by davidromani** [comment]
@egeloen can you type me a hint about how to implement the workarround?

**Comment by benschumi** [comment]
Use assets instead of getPath

**Comment by egeloen** [comment]
Hum maybe I don't have understand well your issue... Are you talking about the marker clusterer icon (eg the icon which groups markers) or a single marker icon (eg img/kinder-marker.png) ?

**Comment by davidromani** [comment]
I'm talking about the marker clusterer icon. My custom marker icon works well.

**Comment by egeloen** [comment]
Ok, so, after re-reading the marker clusterer doc, it seems the library has evolved and I need to fix something here...

Aaccording to this [README](https://github.com/googlemaps/js-marker-clusterer#usage), you can use the following javascript:

``` js
// Init map and markers
var options = {
    imagePath: 'images/m'
};

var markerCluster = new MarkerClusterer(map, markers, options);
```

So, you can use the `imagePath` marker clusterer option in order to customize the image path:

``` php
$map->getOverlayManager()->getMarkerCluster()->setOption('imagePath', '/path/to/your/asset')
```

The available assets are here: https://github.com/googlemaps/js-marker-clusterer/tree/gh-pages/images

**Comment by davidromani** [comment]
@egeloen thanks, it works!

**Comment by egeloen** [comment]
Reopening as there is somethinng to patch as it does not work natively... The current issue is the marker clusterer library  takes the predicate you will download the library and integrate it to your app (with the assets) whereas the ivory google map only loads the marker clusterer library (javascript) without the assets...

I see two solutions:
 - Let it as it is and document the issue which explain to download assets locally and configure them or rely on online assets by using https://github.com/googlemaps/js-marker-clusterer/tree/gh-pages/images as imagePath).
 - Automatically configure the online assets by using https://github.com/googlemaps/js-marker-clusterer/tree/gh-pages/images as imagePath and document that by default it relies on github assets and let user choose it he wants to download the assets or not (but it works natively)

Personally, I prefer the second solution as it would make it working by default.

**Comment by egeloen** [comment]
I will fix it with the second option since we already rely on github assets: https://github.com/egeloen/ivory-google-map/blob/master/src/Helper/Renderer/Overlay/MarkerClustererRenderer.php#L87
