### ISSUE TITLE
3.0 release

### ISSUE THREAD

**Issue by davidromani** [egeloen/IvoryGoogleMapBundle#197]
Hi. Is there any date to release a 3.x stable tag?

**Comment by egeloen** [comment]
I know, I know, I know, I'm very late on this topic but I prefer take my time to be sure of the API :) Basically, I need to finish egeloen/ivory-google-map#177 and I would like to give a try to egeloen/ivory-google-map#201 before release the next major release.

**Comment by egeloen** [comment]
@davidromani I just release the 3.0.0 :tada: Enjoy!
