### ISSUE TITLE
Class 'Ivory\GoogleMap\Places\Autocomplete' not found

### ISSUE THREAD

**Issue by pckz** [egeloen/IvoryGoogleMapBundle#205]
Hello!
I have been using your lib in my proyect (Laravel Framework version 5.1.45 (LTS)) for like a year, many thanks! very useful

Yesterday (after a lot of time) I updated all my libs with composer update, and I just realized that Autocomplete class fails when I tried to load the component

I got **Class 'Ivory\GoogleMap\Places\Autocomplete' not found**

So I found in google the issue and this link has helped me: https://github.com/egeloen/IvoryGoogleMapBundle/issues/106

And using the following versions is working now again

        "egeloen/google-map": "~1.4@dev",
        "egeloen/google-map-bundle": "~2.2@dev",

My question is about the latest versions compatible.. because the link and the responses are from 2014.
I tried with "~2.0@dev" and "~3.0@dev" respectively, or "dev-master" for both and I got the same error as that Autocomplete class not found.

So.. what are the latest versions that I have to use to not receive the error, and in same time not be so outdated?

Thanks!

**Comment by egeloen** [comment]
Basically, it will not be an easy topic... AFAIR, autocomplete requires an api key which is not supported on 2.x version of the bundle... Are you able to use the autocomplete type without an api key? 

The only way I see to make it working is to upgrade your code and make it compatible with the 3.x version of the bundle...

**Comment by egeloen** [comment]
@pckz Does my answer fix your issue?
