### ISSUE TITLE
symfony2 do not reconize service ivory.google_map.direction

### ISSUE THREAD

**Issue by mathieuTripblan** [egeloen/IvoryGoogleMapBundle#206]
Please can you help me?

I created a service named "googledirections.manager and i wanted to inject "ivory.google_map.direction" in this service. but when i want use this service i got this error:

The service "googledirections.manager" has a dependency on a non-existent service "ivory.google_map.direction".

I'am using symfony 2.7 
here is my composer.json

{
    "name": "root/aaaaa",
    "license": "proprietary",
    "type": "project",
    "autoload": {
        "psr-4": {
            "": "src/"
        }
    },
    "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.7.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "leaseweb/api-caller-bundle": "*",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "friendsofsymfony/jsrouting-bundle": "^1.5",
        "liip/imagine-bundle": "^1.3",
        "stof/doctrine-extensions-bundle": "^1.2",
        "friendsofsymfony/elastica-bundle": "^3.1",
        "jms/serializer-bundle": "^1.1",
        "friendsofsymfony/rest-bundle": "^1.7",
        "nelmio/api-doc-bundle": "@dev",
        "friendsofsymfony/comment-bundle": "^2.0",
        "lexik/jwt-authentication-bundle" : "^1.4",
        "jcroll/foursquare-api-bundle": "1.0.*",
        "willdurand/geocoder-bundle": "@stable",
        "maxmind/geoip": "dev-master",
        "beberlei/DoctrineExtensions": "^1.0",
        "doctrine/doctrine-cache-bundle": "^1.3",
        "symfony/proxy-manager-bridge": "~2.3",
        "ocramius/proxy-manager": "~1.0",
        "jms/i18n-routing-bundle": "^2.0",
        "jms/translation-bundle": "^1.2",
        "yucca/prerender-bundle": "0.1.*@dev",
        "presta/sitemap-bundle": "^1.5",
        "ricbra/robots-txt-bundle": "1.0.0",
        "egeloen/google-map-bundle": "^3.0",
        "egeloen/serializer-bundle": "^1.0",
        "php-http/guzzle6-adapter": "^1.1",
        "php-http/message": "^1.5"
    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3",
        "escapestudios/symfony2-coding-standard": "~2.0",
        "doctrine/doctrine-fixtures-bundle": "^2.3",
        "jns/xhprof-bundle": "1.0.*@dev",
        "lox/xhprof": "dev-master@dev",
        "phpunit/phpunit": "^4.8",
        "phpmd/phpmd" : "^2.4"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "config": {
        "bin-dir": "bin"
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        }
    }
}

**Comment by egeloen** [comment]
@mathieuTripblan Have you configured the service as explain here: https://github.com/egeloen/IvoryGoogleMapBundle/blob/master/Resources/doc/service/directions.md#configuration ?

**Comment by egeloen** [comment]
ping @mathieuTripblan

**Comment by egeloen** [comment]
Closing as there is no feedback
