### ISSUE TITLE
Incorrect description for autocomplete for restriction by country

### ISSUE THREAD

**Issue by AlexBykovski** [egeloen/IvoryGoogleMapBundle#207]
I tried to use like described here https://github.com/egeloen/IvoryGoogleMapBundle/blob/master/Resources/doc/place_autocomplete.md#configure-components, but I got an error `The option "country" does not exist. `

Then I checked code and found out that it should be in documentation:
$builder->add('field', PlaceAutocompleteType::class, [
    'components' => [AutocompleteComponentType::COUNTRY => 'fr']
]);

Please, add it.

**Comment by egeloen** [comment]
@AlexBykovski Thanks for your feedbacks. Writing good code is hard but writing good docs (without typos) is even harder... :) Can you make a PR to fix it?

**Comment by AlexBykovski** [comment]
@egeloen I tried, but seems that I haven't access 
![image](https://cloud.githubusercontent.com/assets/7932019/23971127/b229b9f4-09dd-11e7-8c4a-afb744e2dfc5.png)

**Comment by AlexBykovski** [comment]
BTW, thank you for this bundle, I used it and very satisfied. Good work! 👍

**Comment by egeloen** [comment]
@AlexBykovski You can't push directly to this repository. Instead you need first to fork it (https://help.github.com/articles/fork-a-repo/) and then create a PR (https://help.github.com/articles/creating-a-pull-request/) that I will review and merge :)

**Comment by egeloen** [comment]
Your issue has been fixed by 341047680ee643407d274214288283efe3014661
