### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by zabaworld1994** [egeloen/IvoryGoogleMapBundle#208]
How Can I access to JavaScript Variable in Symfony 3 Eric GELOEN
setJavascriptVariable() method does not exit help please

**Comment by egeloen** [comment]
@zabaworld1994 You need to rely on `setVariable` instead.

**Comment by zabaworld1994** [comment]
thank you sir for you fast reply please can you help me  more i  did setVariable("mymap") in then controller 
now please how can i get the google map objet in the twig view to use javascript code

**Comment by egeloen** [comment]
Just pass it to the view as you would pass any template variables and then use the helpers according to you templating framework (Twig or PHP) (as documented [here](https://github.com/egeloen/IvoryGoogleMapBundle/blob/master/Resources/doc/map.md#render)).

**Comment by zabaworld1994** [comment]
thank you Issue resolved problem was using document.ready fires too early 
using window.load everything worked great
