### ISSUE TITLE
Composer install problem

### ISSUE THREAD

**Issue by oceandesk** [egeloen/IvoryGoogleMapBundle#209]
If I try to install google-maps

  Problem 1
    - egeloen/google-map 2.0.x-dev requires php ^5.6|^7.0 -> your PHP version (5.6.24) overridden by "config.platform.php" version (5.5.9) does not satisfy that requirement.
    - egeloen/google-map 2.0.1 requires php ^5.6|^7.0 -> your PHP version (5.6.24) overridden by "config.platform.php" version (5.5.9) does not satisfy that requirement.
    - egeloen/google-map 2.0.0 requires php ^5.6|^7.0 -> your PHP version (5.6.24) overridden by "config.platform.php" version (5.5.9) does not satisfy that requirement.
    - Installation request for egeloen/google-map ^2.0@dev -> satisfiable by egeloen/google-map[2.0.0, 2.0.1, 2.0.x-dev].

**Comment by egeloen** [comment]
It seems you have downloaded a fresh install of symfony and your `composer.json` relies on an explicit PHP version. Remove the `config.platform.php` node in your `composer.json` and everything should be fine :)

**Comment by oceandesk** [comment]
thank you

**Comment by egeloen** [comment]
Closing as it seems the issue is fixed
