### ISSUE TITLE
Using events on form collections including index

### ISSUE THREAD

**Issue by ScherlOMatic** [egeloen/IvoryGoogleMapBundle#210]
Hello!

Thx again for helping me out last time.
I ran into a new let's call it problem while adding entities dynamically.

Class structure looks like this: Order has multiple Products. Where products contain the PlaceAutocompleteType.
The event is this:
`function (e) {
    document.getElementById("order_products___name___place").value = JSON.stringify(this.getPlace()); 
}`

As you can see I need the index of the current colletion within the event. I'm not sure there is an easy method to access the index from within the event. So what I did was to replace the index by a placeholder called "__name__".
This works fine cause also the prototype function from symfony works with it and replaces __name__ dynamically before adding it via javascript.

Sounds great, doesn't it?
But the first collection has still the __name__ living inside of the javascript.
My workaround to fix it this is not the best so I'm asking for your opinion.

`{{ form_row(job.location)|replace({'__name__': loop.index0})|raw }}`

place is a hidden variable where i save the google place details into
location is the placeautocomplete type

thx for your advice

**Comment by egeloen** [comment]
@ScherlOMatic Where does come from the event? You put it in your own javascript?

**Comment by ScherlOMatic** [comment]
Nope, I put it inside my Symfony Form Type. See #196 for more details about the event itself.

**Comment by egeloen** [comment]
I don't see an easy solution as the prototype coming from symfony does not expose such information to javascript... You will need to live with your "workaround". Closing for now but if someone dig into this issue and find a nicer solution, share it :)
