### ISSUE TITLE
No more Stylesheet on Map ?

### ISSUE THREAD

**Issue by Nachkaa** [egeloen/IvoryGoogleMapBundle#216]
Hi ! 

I think there is no more
`$map->setStylesheet('position', 'absolute');`

I have this error 

> 'Attempted to call an undefined method named "setStylesheet" of class "Ivory\GoogleMap\Map".
> Did you mean to call e.g. "setStylesheetOption" or "setStylesheetOptions"

My Controller Code has 
```
use Ivory\GoogleMap\Map;
.
.
.
$map = new Map();

$map->setVariable('map');
$map->setHtmlId('google-map');
$map->setStylesheet('position', 'absolute');
```
Maybe I wrong :)

**Comment by egeloen** [comment]
This is now called `setStylesheetOption` as the Symfony debug component proposes you :)

**Comment by Nachkaa** [comment]
haha my bad :) thank you !
